// --- Lista para Inglés -> Español ---
// Contiene objetos con: { eng: "Palabra en Inglés", esp: "Traducción Español", unit: "Unidad" }
const listaIngEsp = [
  { eng: "foolproof", esp: "infalible", unit: "File 1" },
  { eng: "geek", esp: "friki", unit: "File 1" },
  { eng: "good-natured rivalry", esp: "rivalidad sana", unit: "File 1" },
  { eng: "gut feeling", esp: "intuición", unit: "File 1" },
  { eng: "job-seeker", esp: "solicitante de empleo", unit: "File 1" },
  { eng: "light-hearted response", esp: "respuesta desenfadada", unit: "File 1" },
  { eng: "the point of", esp: "la cuestión", unit: "File 1" },
  { eng: "work–life balance", esp: "equilibrio entre la vida personal y laboral", unit: "File 1" },
  { eng: "absent-minded", esp: "distraído", unit: "File 1" },
  { eng: "bad-tempered", esp: "de mal humor", unit: "File 1" },
  { eng: "big-headed", esp: "engreído", unit: "File 1" },
  { eng: "easy-going", esp: "de trato fácil", unit: "File 1" },
  { eng: "good-tempered", esp: "sereno", unit: "File 1" },
  { eng: "laid-back", esp: "despreocupado", unit: "File 1" },
  { eng: "narrow-minded", esp: "estrecho de miras", unit: "File 1" },
  { eng: "open-minded", esp: "abierto de mente", unit: "File 1" },
  { eng: "self-centred", esp: "egocéntrico", unit: "File 1" },
  { eng: "strong-willed", esp: "de fuerte carácter", unit: "File 1" },
  { eng: "tight-fisted", esp: "agarrado", unit: "File 1" },
  { eng: "two-faced", esp: "una persona falsa", unit: "File 1" },
  { eng: "well-balanced", esp: "equilibrado", unit: "File 1" },
  { eng: "well-behaved", esp: "bien educados", unit: "File 1" },
  { eng: "allergic reaction", esp: "reacción alérgica", unit: "File 2" },
  { eng: "be sick", esp: "ponerse enfermo", unit: "File 2" },
  { eng: "bleed", esp: "sangrar", unit: "File 2" },
  { eng: "blister", esp: "ampolla", unit: "File 2" },
  { eng: "(high / low) blood pressure", esp: "presión arterial (alta/baja)", unit: "File 2" },
  { eng: "burn", esp: "quemar", unit: "File 2" },
  { eng: "choke", esp: "atragantarse", unit: "File 2" },
  { eng: "cold", esp: "resfriado", unit: "File 2" },
  { eng: "come round", esp: "volver en sí", unit: "File 2" },
  { eng: "cough", esp: "tos", unit: "File 2" },
  { eng: "cut", esp: "cortarse", unit: "File 2" },
  { eng: "diarrhoea", esp: "diarrea", unit: "File 2" },
  { eng: "dizzy", esp: "mareado", unit: "File 2" },
  { eng: "earache", esp: "dolor de oído", unit: "File 2" },
  { eng: "faint", esp: "desmayarse", unit: "File 2" },
  { eng: "feel sick", esp: "sentirse enfermo", unit: "File 2" },
  { eng: "flu", esp: "gripe", unit: "File 2" },
  { eng: "food poisoning", esp: "intoxicación alimentaria", unit: "File 2" },
  { eng: "get over", esp: "curarse (de)", unit: "File 2" },
  { eng: "headache", esp: "dolor de cabeza", unit: "File 2" },
  { eng: "hurt", esp: "doler", unit: "File 2" },
  { eng: "lie down", esp: "echarse", unit: "File 2" },
  { eng: "pass out", esp: "desmayarse", unit: "File 2" },
  { eng: "rash", esp: "sarpullido", unit: "File 2" },
  { eng: "sore throat", esp: "dolor de garganta", unit: "File 2" },
  { eng: "sprain", esp: "torcer(se)", unit: "File 2" },
  { eng: "stomach ache", esp: "dolor de estómago", unit: "File 2" },
  { eng: "sunburn", esp: "quemarse por el sol", unit: "File 2" },
  { eng: "swell", esp: "dar de sí", unit: "File 2" },
  { eng: "temperature", esp: "temperatura", unit: "File 2" },
  { eng: "throw up", esp: "vomitar", unit: "File 2" },
  { eng: "toothache", esp: "dolor de muelas", unit: "File 2" },
  { eng: "unconscious", esp: "inconsciente", unit: "File 2" },
  { eng: "vomit", esp: "vomitar", unit: "File 2" },
  { eng: "casual", esp: "informal", unit: "File 2" },
  { eng: "checked", esp: "de cuadros", unit: "File 2" },
  { eng: "classic", esp: "clásico", unit: "File 2" },
  { eng: "cotton vest", esp: "camiseta de algodón", unit: "File 2" },
  { eng: "denim waistcoat", esp: "chaleco vaquero", unit: "File 2" },
  { eng: "dress up", esp: "arreglarse", unit: "File 2" },
  { eng: "fit", esp: "quedar bien (algo)", unit: "File 2" },
  { eng: "fur collar", esp: "estola de piel", unit: "File 2" },
  { eng: "get changed", esp: "cambiarse", unit: "File 2" },
  { eng: "get dressed", esp: "vestirse", unit: "File 2" },
  { eng: "get undressed", esp: "quitar(se) la ropa", unit: "File 2" },
  { eng: "go with", esp: "pegar (con)", unit: "File 2" },
  { eng: "hang up", esp: "colgar", unit: "File 2" },
  { eng: "hooded", esp: "con capucha", unit: "File 2" },
  { eng: "lace top", esp: "top de encaje", unit: "File 2" },
  { eng: "leather sandals", esp: "sandalias de cuero", unit: "File 2" },
  { eng: "linen suit", esp: "traje de lino", unit: "File 2" },
  { eng: "long-sleeved", esp: "de manga larga", unit: "File 2" },
  { eng: "loose", esp: "holgado", unit: "File 2" },
  { eng: "lycra swimsuit", esp: "bañador de lycra", unit: "File 2" },
  { eng: "match", esp: "ir a juego", unit: "File 2" },
  { eng: "old-fashioned", esp: "anticuado", unit: "File 2" },
  { eng: "patterned", esp: "estampado", unit: "File 2" },
  { eng: "plain", esp: "liso", unit: "File 2" },
  { eng: "scruffy", esp: "desaliñado", unit: "File 2" },
  { eng: "silk scarf", esp: "pañuelo de seda", unit: "File 2" },
  { eng: "sleeveless", esp: "sin mangas", unit: "File 2" },
  { eng: "smart", esp: "elegante", unit: "File 2" },
  { eng: "spotted", esp: "de lunares", unit: "File 2" },
  { eng: "striped", esp: "de rayas", unit: "File 2" },
  { eng: "suede boots", esp: "botas de ante", unit: "File 2" },
  { eng: "suit", esp: "quedar bien (algo)", unit: "File 2" },
  { eng: "tight", esp: "apretado", unit: "File 2" },
  { eng: "velvet bow tie", esp: "pajarita de terciopelo", unit: "File 2" },
  { eng: "V-neck", esp: "cuello de pico", unit: "File 2" },
  { eng: "wool(len) cardigan", esp: "rebeca de lana", unit: "File 2" },
  { eng: "airport terminal", esp: "terminal de aeropuerto", unit: "File 3" },
  { eng: "aisle", esp: "pasillo", unit: "File 3" },
  { eng: "bag(gage) drop", esp: "mostrador de equipajes", unit: "File 3" },
  { eng: "baggage reclaim", esp: "recogida de equipajes", unit: "File 3" },
  { eng: "board", esp: "embarcar", unit: "File 3" },
  { eng: "boarding pass", esp: "tarjeta de embarque", unit: "File 3" },
  { eng: "business", esp: "business", unit: "File 3" },
  { eng: "cabin crew", esp: "personal de cabina", unit: "File 3" },
  { eng: "check", esp: "inspeccionar", unit: "File 3" },
  { eng: "check in", esp: "facturar", unit: "File 3" },
  { eng: "check-in desk", esp: "mostrador de facturación", unit: "File 3" },
  { eng: "closed", esp: "cerrado", unit: "File 3" },
  { eng: "collect", esp: "recoger", unit: "File 3" },
  { eng: "connecting flight", esp: "vuelo de enlace", unit: "File 3" },
  { eng: "customs", esp: "aduana", unit: "File 3" },
  { eng: "delayed", esp: "retrasado", unit: "File 3" },
  { eng: "departures board", esp: "panel de salidas", unit: "File 3" },
  { eng: "direct flight", esp: "vuelo directo", unit: "File 3" },
  { eng: "drop off", esp: "llevar (a alguien)", unit: "File 3" },
  { eng: "first class", esp: "primera clase", unit: "File 3" },
  { eng: "flight time", esp: "hora del vuelo", unit: "File 3" },
  { eng: "fill in", esp: "rellenar", unit: "File 3" },
  { eng: "gate", esp: "puerta", unit: "File 3" },
  { eng: "get off", esp: "bajar(se) (de algo)", unit: "File 3" },
  { eng: "get on", esp: "subir(se) (a algo)", unit: "File 3" },
  { eng: "hand luggage", esp: "equipaje de mano", unit: "File 3" },
  { eng: "illegal goods", esp: "productos ilegales", unit: "File 3" },
  { eng: "jet lag", esp: "desfase horario", unit: "File 3" },
  { eng: "journey", esp: "viaje", unit: "File 3" },
  { eng: "land", esp: "aterrizar", unit: "File 3" },
  { eng: "liquid", esp: "líquido", unit: "File 3" },
  { eng: "long-haul flight", esp: "vuelo de larga distancia", unit: "File 3" },
  { eng: "(airline) lounge", esp: "sala (de compañía aérea)", unit: "File 3" },
  { eng: "luggage", esp: "equipaje", unit: "File 3" },
  { eng: "on time", esp: "puntual", unit: "File 3" },
  { eng: "pick up", esp: "recoger (algo)", unit: "File 3" },
  { eng: "pick up", esp: "recoger (a alguien)", unit: "File 3" },
  { eng: "row", esp: "fila", unit: "File 3" },
  { eng: "runway", esp: "pista", unit: "File 3" },
  { eng: "scan", esp: "pasar por el escáner", unit: "File 3" },
  { eng: "seat belt", esp: "cinturón de seguridad", unit: "File 3" },
  { eng: "security", esp: "seguridad", unit: "File 3" },
  { eng: "sharp object", esp: "objeto punzante", unit: "File 3" },
  { eng: "take off", esp: "despegar", unit: "File 3" },
  { eng: "travel", esp: "viajar", unit: "File 3" },
  { eng: "trip", esp: "viaje", unit: "File 3" },
  { eng: "trolley", esp: "carrito", unit: "File 3" },
  { eng: "turbulence", esp: "turbulencia", unit: "File 3" },
  { eng: "actually", esp: "en realidad", unit: "File 3" },
  { eng: "apparently", esp: "al parecer", unit: "File 3" },
  { eng: "at the end", esp: "al final", unit: "File 3" },
  { eng: "at the moment", esp: "en estos momentos", unit: "File 3" },
  { eng: "basically", esp: "sencillamente", unit: "File 3" },
  { eng: "certainly", esp: "desde luego", unit: "File 3" },
  { eng: "especially", esp: "especialmente", unit: "File 3" },
  { eng: "even", esp: "incluso", unit: "File 3" },
  { eng: "eventually", esp: "al final", unit: "File 3" },
  { eng: "ever", esp: "alguna vez", unit: "File 3" },
  { eng: "gradually", esp: "poco a poco", unit: "File 3" },
  { eng: "hard", esp: "duro", unit: "File 3" },
  { eng: "hardly", esp: "apenas", unit: "File 3" },
  { eng: "ideally", esp: "(lo) ideal", unit: "File 3" },
  { eng: "in fact", esp: "en realidad", unit: "File 3" },
  { eng: "in the end", esp: "al final", unit: "File 3" },
  { eng: "late", esp: "tarde", unit: "File 3" },
  { eng: "lately", esp: "últimamente", unit: "File 3" },
  { eng: "near", esp: "cerca", unit: "File 3" },
  { eng: "nearly", esp: "casi", unit: "File 3" },
  { eng: "obviously", esp: "obviamente", unit: "File 3" },
  { eng: "specially", esp: "expresamente", unit: "File 3" },
  { eng: "still", esp: "todavía", unit: "File 3" },
  { eng: "yet", esp: "aún", unit: "File 3" },
  { eng: "below zero", esp: "bajo cero", unit: "File 4" },
  { eng: "blizzard", esp: "ventisca", unit: "File 4" },
  { eng: "boiling", esp: "hacer un calor sofocante", unit: "File 4" },
  { eng: "breeze", esp: "brisa", unit: "File 4" },
  { eng: "bright", esp: "brillante", unit: "File 4" },
  { eng: "changeable", esp: "variable", unit: "File 4" },
  { eng: "chilly", esp: "fresco", unit: "File 4" },
  { eng: "clear", esp: "despejado", unit: "File 4" },
  { eng: "cool", esp: "fresco", unit: "File 4" },
  { eng: "damp", esp: "húmedo", unit: "File 4" },
  { eng: "drizzle", esp: "lloviznar", unit: "File 4" },
  { eng: "drought", esp: "sequía", unit: "File 4" },
  { eng: "flood", esp: "inundación", unit: "File 4" },
  { eng: "fog", esp: "niebla", unit: "File 4" },
  { eng: "freezing", esp: "hacer mucho frío", unit: "File 4" },
  { eng: "hail", esp: "granizo", unit: "File 4" },
  { eng: "heatwave", esp: "ola de calor", unit: "File 4" },
  { eng: "heavy", esp: "intenso", unit: "File 4" },
  { eng: "humid", esp: "húmedo", unit: "File 4" },
  { eng: "hurricane", esp: "huracán", unit: "File 4" },
  { eng: "icy", esp: "helado", unit: "File 4" },
  { eng: "lightning", esp: "relámpago", unit: "File 4" },
  { eng: "mild", esp: "templado", unit: "File 4" },
  { eng: "mist", esp: "neblina", unit: "File 4" },
  { eng: "monsoon", esp: "monzón", unit: "File 4" },
  { eng: "pour (with rain)", esp: "llover a mares", unit: "File 4" },
  { eng: "settled", esp: "estable", unit: "File 4" },
  { eng: "shower", esp: "tormenta", unit: "File 4" },
  { eng: "smog", esp: "contaminación", unit: "File 4" },
  { eng: "strong", esp: "fuerte", unit: "File 4" },
  { eng: "sunny", esp: "soleado", unit: "File 4" },
  { eng: "thick", esp: "denso", unit: "File 4" },
  { eng: "thunder", esp: "trueno", unit: "File 4" },
  { eng: "warm", esp: "calor", unit: "File 4" },
  { eng: "take advantage of", esp: "aprovechar", unit: "File 4" },
  { eng: "take after", esp: "parecerse (a alguien)", unit: "File 4" },
  { eng: "take against", esp: "estar enfadado", unit: "File 4" },
  { eng: "take care of", esp: "encargarse de", unit: "File 4" },
  { eng: "take into account", esp: "tener en cuenta", unit: "File 4" },
  { eng: "take no notice of", esp: "no hacer caso de", unit: "File 4" },
  { eng: "take off", esp: "despegar", unit: "File 4" },
  { eng: "take (sth) off", esp: "quitarse (algo)", unit: "File 4" },
  { eng: "take (sb) out", esp: "llevar (a alguien)", unit: "File 4" },
  { eng: "take (sth) out", esp: "sacar (fuera)", unit: "File 4" },
  { eng: "take part in", esp: "participar en", unit: "File 4" },
  { eng: "take pity on", esp: "apiadarse de", unit: "File 4" },
  { eng: "take place", esp: "tener lugar", unit: "File 4" },
  { eng: "take risks", esp: "tomar riesgos", unit: "File 4" },
  { eng: "take (your) time", esp: "tomarse el tiempo necesario", unit: "File 4" },
  { eng: "take to", esp: "encariñarse con", unit: "File 4" },
  { eng: "take up", esp: "empezar a hacer algo", unit: "File 4" },
  { eng: "astonished", esp: "asombrado", unit: "File 5" },
  { eng: "bewildered", esp: "perplejo", unit: "File 5" },
  { eng: "delighted", esp: "encantado", unit: "File 5" },
  { eng: "desperate", esp: "desesperado", unit: "File 5" },
  { eng: "devastated", esp: "devastado", unit: "File 5" },
  { eng: "disappointed", esp: "decepcionado", unit: "File 5" },
  { eng: "down", esp: "decaído", unit: "File 5" },
  { eng: "fed up", esp: "harto", unit: "File 5" },
  { eng: "gobsmacked", esp: "atónito", unit: "File 5" },
  { eng: "grateful", esp: "agradecido", unit: "File 5" },
  { eng: "gutted", esp: "quedarse hecho polvo", unit: "File 5" },
  { eng: "homesick", esp: "tener nostalgia", unit: "File 5" },
  { eng: "horrifed", esp: "horrorizado", unit: "File 5" },
  { eng: "lonely", esp: "solo", unit: "File 5" },
  { eng: "miserable", esp: "abatido", unit: "File 5" },
  { eng: "offended", esp: "ofendido", unit: "File 5" },
  { eng: "overwhelmed", esp: "abrumado", unit: "File 5" },
  { eng: "proud", esp: "orgulloso", unit: "File 5" },
  { eng: "relieved", esp: "aliviado", unit: "File 5" },
  { eng: "scared stiff", esp: "muerto de miedo", unit: "File 5" },
  { eng: "shattered", esp: "hecho añicos", unit: "File 5" },
  { eng: "sick of", esp: "harto de", unit: "File 5" },
  { eng: "stunned", esp: "aturdido", unit: "File 5" },
  { eng: "thrilled", esp: "entusiasmado", unit: "File 5" },
  { eng: "upset", esp: "disgustado", unit: "File 5" },
  { eng: "amaze", esp: "asombrar", unit: "File 5" },
  { eng: "confuse", esp: "confundir", unit: "File 5" },
  { eng: "disappoint", esp: "decepcionar", unit: "File 5" },
  { eng: "embarrass", esp: "avergonzar", unit: "File 5" },
  { eng: "exhaust", esp: "agotado", unit: "File 5" },
  { eng: "frustrate", esp: "frustrar", unit: "File 5" },
  { eng: "infuriate", esp: "enfurecer", unit: "File 5" },
  { eng: "inspire", esp: "inspirar", unit: "File 5" },
  { eng: "terrify", esp: "aterrorizar", unit: "File 5" },
  { eng: "thrill", esp: "hacer (mucha) ilusión", unit: "File 5" },
  { eng: "be a light sleeper", esp: "tener un sueño ligero", unit: "File 6" },
  { eng: "be fast asleep", esp: "dormirse rápido", unit: "File 6" },
  { eng: "blanket", esp: "manta", unit: "File 6" },
  { eng: "duvet", esp: "edredón", unit: "File 6" },
  { eng: "fall asleep", esp: "dormirse", unit: "File 6" },
  { eng: "have nightmares", esp: "tener pesadillas", unit: "File 6" },
  { eng: "insomnia", esp: "insomnio", unit: "File 6" },
  { eng: "keep you awake", esp: "impedir dormir", unit: "File 6" },
  { eng: "nap", esp: "siesta", unit: "File 6" },
  { eng: "oversleep", esp: "quedarse dormido", unit: "File 6" },
  { eng: "pillow", esp: "almohada", unit: "File 6" },
  { eng: "set the alarm", esp: "poner la alarma", unit: "File 6" },
  { eng: "sheet", esp: "sábana", unit: "File 6" },
  { eng: "sleeping pill", esp: "pastilla para dormir", unit: "File 6" },
  { eng: "sleep like a log", esp: "dormir como un tronco", unit: "File 6" },
  { eng: "sleepwalk", esp: "ser sonámbulo", unit: "File 6" },
  { eng: "sleepy", esp: "tener sueño", unit: "File 6" },
  { eng: "snore", esp: "roncar", unit: "File 6" },
  { eng: "yawn", esp: "bostezar", unit: "File 6" },
  { eng: "architecture", esp: "arquitectura", unit: "File 6" },
  { eng: "ballet", esp: "ballet", unit: "File 6" },
  { eng: "barista", esp: "barista", unit: "File 6" },
  { eng: "bass guitar", esp: "bajo", unit: "File 6" },
  { eng: "bouquet", esp: "ramo", unit: "File 6" },
  { eng: "cappuccino", esp: "capuchino", unit: "File 6" },
  { eng: "cello", esp: "violonchelo", unit: "File 6" },
  { eng: "chauffeur", esp: "chófer", unit: "File 6" },
  { eng: "chef", esp: "chef", unit: "File 6" },
  { eng: "chic", esp: "elegante", unit: "File 6" },
  { eng: "choir", esp: "coro", unit: "File 6" },
  { eng: "chorus", esp: "estribillo", unit: "File 6" },
  { eng: "concerto", esp: "concierto", unit: "File 6" },
  { eng: "conductor", esp: "director", unit: "File 6" },
  { eng: "croissant", esp: "croissant", unit: "File 6" },
  { eng: "drum", esp: "tambor", unit: "File 6" },
  { eng: "encore", esp: "bis", unit: "File 6" },
  { eng: "fiancé", esp: "prometido", unit: "File 6" },
  { eng: "flute", esp: "flauta", unit: "File 6" },
  { eng: "genre", esp: "género", unit: "File 6" },
  { eng: "graffiti", esp: "grafiti", unit: "File 6" },
  { eng: "hypochondriac", esp: "hipocondríaco", unit: "File 6" },
  { eng: "keyboard", esp: "teclado", unit: "File 6" },
  { eng: "macchiato", esp: "macchiato", unit: "File 6" },
  { eng: "mezzo-soprano", esp: "mezzo-soprano", unit: "File 6" },
  { eng: "microphone", esp: "micrófono", unit: "File 6" },
  { eng: "orchestra", esp: "orquesta", unit: "File 6" },
  { eng: "paparazzi", esp: "paparazzi", unit: "File 6" },
  { eng: "philosophy", esp: "filosofía", unit: "File 6" },
  { eng: "psychic", esp: "adivino", unit: "File 6" },
  { eng: "psychologist", esp: "psicólogo", unit: "File 6" },
  { eng: "rhythm", esp: "ritmo", unit: "File 6" },
  { eng: "saxophone", esp: "saxofón", unit: "File 6" },
  { eng: "soprano", esp: "soprano", unit: "File 6" },
  { eng: "symphony", esp: "sinfonía", unit: "File 6" },
  { eng: "villa", esp: "chalet", unit: "File 6" },
  { eng: "violin", esp: "violín", unit: "File 6" },
  { eng: "advise", esp: "aconsejar", unit: "File 7" },
  { eng: "argue", esp: "argumentar", unit: "File 7" },
  { eng: "avoid", esp: "evitar", unit: "File 7" },
  { eng: "beat", esp: "derrotar", unit: "File 7" },
  { eng: "borrow", esp: "pedir prestado", unit: "File 7" },
  { eng: "deny", esp: "negar", unit: "File 7" },
  { eng: "discuss", esp: "hablar (de algo)", unit: "File 7" },
  { eng: "expect", esp: "esperar", unit: "File 7" },
  { eng: "hope", esp: "esperar", unit: "File 7" },
  { eng: "lay (past laid)", esp: "poner (la mesa...)", unit: "File 7" },
  { eng: "lend", esp: "prestar", unit: "File 7" },
  { eng: "lie (past lay)", esp: "tumbarse", unit: "File 7" },
  { eng: "matter", esp: "importar", unit: "File 7" },
  { eng: "mind", esp: "importar", unit: "File 7" },
  { eng: "notice", esp: "darse cuenta", unit: "File 7" },
  { eng: "prevent", esp: "impedir", unit: "File 7" },
  { eng: "raise", esp: "subir", unit: "File 7" },
  { eng: "realize", esp: "darse cuenta (de)", unit: "File 7" },
  { eng: "refuse", esp: "negarse", unit: "File 7" },
  { eng: "remember", esp: "acordarse (de)", unit: "File 7" },
  { eng: "remind", esp: "recordar (algo a alguien)", unit: "File 7" },
  { eng: "rise", esp: "subir", unit: "File 7" },
  { eng: "rob", esp: "robar", unit: "File 7" },
  { eng: "steal", esp: "robar", unit: "File 7" },
  { eng: "wait", esp: "esperar", unit: "File 7" },
  { eng: "warn", esp: "advertir", unit: "File 7" },
  { eng: "win", esp: "ganar", unit: "File 7" },
  { eng: "wish", esp: "ojalá", unit: "File 7" },
  { eng: "ankle", esp: "tobillo", unit: "File 7" },
  { eng: "bite your nails", esp: "morderse las uñas", unit: "File 7" },
  { eng: "blow your nose", esp: "sonarse la nariz", unit: "File 7" },
  { eng: "bottom", esp: "trasero", unit: "File 7" },
  { eng: "brain", esp: "cerebro", unit: "File 7" },
  { eng: "brush your hair", esp: "cepillarse el pelo", unit: "File 7" },
  { eng: "brush your teeth", esp: "lavarse los dientes", unit: "File 7" },
  { eng: "calf", esp: "pantorrilla", unit: "File 7" },
  { eng: "cheek", esp: "mejilla", unit: "File 7" },
  { eng: "chest", esp: "pecho", unit: "File 7" },
  { eng: "chew", esp: "masticar", unit: "File 7" },
  { eng: "chin", esp: "barbilla", unit: "File 7" },
  { eng: "comb your hair", esp: "peinarse", unit: "File 7" },
  { eng: "elbow", esp: "codo", unit: "File 7" },
  { eng: "eye", esp: "ojo", unit: "File 7" },
  { eng: "eyebrow", esp: "ceja", unit: "File 7" },
  { eng: "eyelash", esp: "pestaña", unit: "File 7" },
  { eng: "eyelid", esp: "párpado", unit: "File 7" },
  { eng: "fist", esp: "puño", unit: "File 7" },
  { eng: "fold your arms", esp: "cruzarse de brazos", unit: "File 7" },
  { eng: "forehead", esp: "frente", unit: "File 7" },
  { eng: "frown", esp: "fruncir el ceño", unit: "File 7" },
  { eng: "heart", esp: "corazón", unit: "File 7" },
  { eng: "heel", esp: "tacón", unit: "File 7" },
  { eng: "hip", esp: "cadera", unit: "File 7" },
  { eng: "hold someone's hand", esp: "coger a alguien de la mano", unit: "File 7" },
  { eng: "hug", esp: "abrazar", unit: "File 7" },
  { eng: "kidneys", esp: "riñón", unit: "File 7" },
  { eng: "knee", esp: "rodilla", unit: "File 7" },
  { eng: "kneel", esp: "arrodillarse", unit: "File 7" },
  { eng: "lips", esp: "labio", unit: "File 7" },
  { eng: "liver", esp: "hígado", unit: "File 7" },
  { eng: "lungs", esp: "pulmón", unit: "File 7" },
  { eng: "nails", esp: "uñas", unit: "File 7" },
  { eng: "neck", esp: "cuello", unit: "File 7" },
  { eng: "palm", esp: "palma", unit: "File 7" },
  { eng: "point", esp: "señalar", unit: "File 7" },
  { eng: "raise your eyebrows", esp: "levantar las cejas", unit: "File 7" },
  { eng: "scratch", esp: "rascar", unit: "File 7" },
  { eng: "shake hands", esp: "darse la mano", unit: "File 7" },
  { eng: "shake your head", esp: "negar con la cabeza", unit: "File 7" },
  { eng: "shrug your shoulders", esp: "encogerse de hombros", unit: "File 7" },
  { eng: "stare", esp: "mirar fijamente", unit: "File 7" },
  { eng: "stretch", esp: "estirar(se)", unit: "File 7" },
  { eng: "stubble", esp: "vello", unit: "File 7" },
  { eng: "suck your thumb", esp: "chuparse el dedo", unit: "File 7" },
  { eng: "thigh", esp: "muslo", unit: "File 7" },
  { eng: "touch your toes", esp: "tocarse los dedos de los pies", unit: "File 7" },
  { eng: "waist", esp: "cintura", unit: "File 7" },
  { eng: "wave", esp: "saludar", unit: "File 7" },
  { eng: "wink", esp: "guiñar el ojo", unit: "File 7" },
  { eng: "wrinkles", esp: "arruga", unit: "File 7" },
  { eng: "wrist", esp: "muñeca", unit: "File 7" },
  { eng: "yawn", esp: "bostezar", unit: "File 7" },
  { eng: "accuse", esp: "acusar", unit: "File 8" },
  { eng: "acquit", esp: "absolver", unit: "File 8" },
  { eng: "arrest", esp: "detener", unit: "File 8" },
  { eng: "blackmail", esp: "chantajear", unit: "File 8" },
  { eng: "bribery", esp: "sobornar", unit: "File 8" },
  { eng: "burglary", esp: "robo (de una casa)", unit: "File 8" },
  { eng: "catch", esp: "atrapar", unit: "File 8" },
  { eng: "charge", esp: "acusar", unit: "File 8" },
  { eng: "commit", esp: "cometer", unit: "File 8" },
  { eng: "court", esp: "tribunal", unit: "File 8" },
  { eng: "drug dealing", esp: "tráfico de drogas", unit: "File 8" },
  { eng: "evidence", esp: "prueba", unit: "File 8" },
  { eng: "fraud", esp: "fraude", unit: "File 8" },
  { eng: "guilty", esp: "culpable", unit: "File 8" },
  { eng: "hacking", esp: "hackeo", unit: "File 8" },
  { eng: "hijacking", esp: "secuestrar", unit: "File 8" },
  { eng: "innocent", esp: "inocente", unit: "File 8" },
  { eng: "investigate", esp: "investigar", unit: "File 8" },
  { eng: "judge", esp: "juez", unit: "File 8" },
  { eng: "jury", esp: "jurado", unit: "File 8" },
  { eng: "kidnapping", esp: "secuestro", unit: "File 8" },
  { eng: "mugging", esp: "asalto", unit: "File 8" },
  { eng: "murder", esp: "asesinato", unit: "File 8" },
  { eng: "proof", esp: "prueba", unit: "File 8" },
  { eng: "punishment", esp: "castigo", unit: "File 8" },
  { eng: "question", esp: "interrogar", unit: "File 8" },
  { eng: "rape", esp: "violación", unit: "File 8" },
  { eng: "robbery", esp: "robo", unit: "File 8" },
  { eng: "sentence", esp: "sentencia", unit: "File 8" },
  { eng: "smuggling", esp: "contrabando", unit: "File 8" },
  { eng: "stalking", esp: "acoso", unit: "File 8" },
  { eng: "terrorism", esp: "terrorismo", unit: "File 8" },
  { eng: "theft", esp: "robo", unit: "File 8" },
  { eng: "vandalism", esp: "vandalismo", unit: "File 8" },
  { eng: "verdict", esp: "veredicto", unit: "File 8" },
  { eng: "witness", esp: "testigo", unit: "File 8" },
  { eng: "accurate", esp: "preciso", unit: "File 8" },
  { eng: "agony aunt", esp: "columnista de consultorio sentimental", unit: "File 8" },
  { eng: "axe", esp: "perder (empleos)", unit: "File 8" },
  { eng: "back", esp: "respaldar", unit: "File 8" },
  { eng: "biased", esp: "parcial", unit: "File 8" },
  { eng: "bid", esp: "intentar", unit: "File 8" },
  { eng: "censored", esp: "censurado", unit: "File 8" },
  { eng: "clash", esp: "discutir", unit: "File 8" },
  { eng: "commentator", esp: "comentarista", unit: "File 8" },
  { eng: "critic", esp: "crítico", unit: "File 8" },
  { eng: "editor", esp: "editor", unit: "File 8" },
  { eng: "freelance journalist", esp: "periodista freelance", unit: "File 8" },
  { eng: "hit", esp: "afectar", unit: "File 8" },
  { eng: "newsreader", esp: "presentador de noticias", unit: "File 8" },
  { eng: "objective", esp: "objetivo", unit: "File 8" },
  { eng: "paparazzi", esp: "paparazzi", unit: "File 8" },
  { eng: "presenter", esp: "presentador", unit: "File 8" },
  { eng: "quit", esp: "dimitir (de)", unit: "File 8" },
  { eng: "quiz", esp: "interrogar", unit: "File 8" },
  { eng: "reporter", esp: "reportero", unit: "File 8" },
  { eng: "row", esp: "discutir", unit: "File 8" },
  { eng: "sensational", esp: "sensacionalista", unit: "File 8" },
  { eng: "split", esp: "separarse", unit: "File 8" },
  { eng: "tip", esp: "predecir", unit: "File 8" },
  { eng: "vow", esp: "prometer", unit: "File 8" },
  { eng: "wed", esp: "casarse (con)", unit: "File 8" },
  { eng: "advertising campaign", esp: "campaña de publicidad", unit: "File 9" },
  { eng: "advertisments", esp: "anuncios", unit: "File 9" },
  { eng: "brand", esp: "marca", unit: "File 9" },
  { eng: "claims", esp: "afirmar", unit: "File 9" },
  { eng: "consumers", esp: "consumidor", unit: "File 9" },
  { eng: "misleading", esp: "engañoso", unit: "File 9" },
  { eng: "publicity", esp: "publicidad", unit: "File 9" },
  { eng: "slogan", esp: "eslogan", unit: "File 9" },
  { eng: "sue", esp: "demandar", unit: "File 9" },
  { eng: "any other business", esp: "algún otro tema", unit: "File 9" },
  { eng: "become the market leader", esp: "convertirse en el líder del mercado", unit: "File 9" },
  { eng: "boom", esp: "explosión", unit: "File 9" },
  { eng: "branch", esp: "sucursal", unit: "File 9" },
  { eng: "chain", esp: "cadena", unit: "File 9" },
  { eng: "close down", esp: "cerrar", unit: "File 9" },
  { eng: "do a deal", esp: "hacer un trato", unit: "File 9" },
  { eng: "do a job", esp: "hacer un trabajo", unit: "File 9" },
  { eng: "do badly", esp: "ir mal", unit: "File 9" },
  { eng: "do business", esp: "hacer negocios", unit: "File 9" },
  { eng: "do market research", esp: "hacer un estudio de mercado", unit: "File 9" },
  { eng: "do well", esp: "hacer (algo) bien", unit: "File 9" },
  { eng: "drop", esp: "disminuir", unit: "File 9" },
  { eng: "expand", esp: "expandir(se)", unit: "File 9" },
  { eng: "export", esp: "exportar", unit: "File 9" },
  { eng: "flop", esp: "fracaso", unit: "File 9" },
  { eng: "get down to business", esp: "ponerse a trabajar", unit: "File 9" },
  { eng: "go out of business", esp: "quebrar (negocio)", unit: "File 9" },
  { eng: "grow", esp: "crecer", unit: "File 9" },
  { eng: "head office", esp: "sede central", unit: "File 9" },
  { eng: "import", esp: "importar", unit: "File 9" },
  { eng: "launch", esp: "lanzamiento", unit: "File 9" },
  { eng: "make a decision", esp: "tomar una decisión", unit: "File 9" },
  { eng: "make a loss", esp: "tener pérdidas", unit: "File 9" },
  { eng: "make a profit", esp: "tener beneficios", unit: "File 9" },
  { eng: "make money", esp: "ganar dinero", unit: "File 9" },
  { eng: "make (sb) redundant", esp: "despedir (a alguien) por exceso de personal", unit: "File 9" },
  { eng: "manufacture", esp: "fabricar", unit: "File 9" },
  { eng: "mean business", esp: "actuar en serio", unit: "File 9" },
  { eng: "merge", esp: "fusionar(se)", unit: "File 9" },
  { eng: "mind your own business", esp: "meterse en sus asuntos", unit: "File 9" },
  { eng: "mix business with pleasure", esp: "mezclar negocios y placer", unit: "File 9" },
  { eng: "none of your business", esp: "no es asunto tuyo", unit: "File 9" },
  { eng: "produce", esp: "producir", unit: "File 9" },
  { eng: "recession", esp: "recesión", unit: "File 9" },
  { eng: "set up", esp: "fundar(se)", unit: "File 9" },
  { eng: "take over", esp: "absorber", unit: "File 9" },
  { eng: "unfinished business", esp: "asunto pendiente", unit: "File 9" },
  { eng: "absence", esp: "ausencia", unit: "File 9" },
  { eng: "abundance", esp: "abundancia", unit: "File 9" },
  { eng: "accommodation", esp: "alojamiento", unit: "File 9" },
  { eng: "alcoholism", esp: "alcoholismo", unit: "File 9" },
  { eng: "antisocial", esp: "antisocial", unit: "File 9" },
  { eng: "autopilot", esp: "piloto automático", unit: "File 9" },
  { eng: "belief", esp: "creencia", unit: "File 9" },
  { eng: "bilingual", esp: "bilingüe", unit: "File 9" },
  { eng: "brotherhood", esp: "fraternidad", unit: "File 9" },
  { eng: "bulletproof", esp: "a prueba de balas", unit: "File 9" },
  { eng: "careful", esp: "tener cuidado", unit: "File 9" },
  { eng: "childhood", esp: "infancia", unit: "File 9" },
  { eng: "coldness", esp: "frío", unit: "File 9" },
  { eng: "connection", esp: "relación", unit: "File 9" },
  { eng: "convenience", esp: "comodidad", unit: "File 9" },
  { eng: "death", esp: "muerte", unit: "File 9" },
  { eng: "development", esp: "desarrollo", unit: "File 9" },
  { eng: "distance", esp: "distancia", unit: "File 9" },
  { eng: "employment", esp: "trabajo", unit: "File 9" },
  { eng: "entertainment", esp: "entretenimiento", unit: "File 9" },
  { eng: "excitement", esp: "emoción", unit: "File 9" },
  { eng: "expectation", esp: "expectativa", unit: "File 9" },
  { eng: "friendliness", esp: "amabilidad", unit: "File 9" },
  { eng: "government", esp: "gobierno", unit: "File 9" },
  { eng: "heat", esp: "calor", unit: "File 9" },
  { eng: "height", esp: "altura", unit: "File 9" },
  { eng: "homeless", esp: "sin techo", unit: "File 9" },
  { eng: "hopeless", esp: "desesperado", unit: "File 9" },
  { eng: "hunger", esp: "hambre", unit: "File 9" },
  { eng: "ignorance", esp: "ignorancia", unit: "File 9" },
  { eng: "improvement", esp: "mejora", unit: "File 9" },
  { eng: "intention", esp: "intención", unit: "File 9" },
  { eng: "loneliness", esp: "soledad", unit: "File 9" },
  { eng: "loss", esp: "pérdida", unit: "File 9" },
  { eng: "megacity", esp: "megaciudad", unit: "File 9" },
  { eng: "misunderstood", esp: "entender mal", unit: "File 9" },
  { eng: "modernism", esp: "modernismo", unit: "File 9" },
  { eng: "monorail", esp: "monorraíl", unit: "File 9" },
  { eng: "multicultural", esp: "multicultural", unit: "File 9" },
  { eng: "neighbourhood", esp: "barrio", unit: "File 9" },
  { eng: "overcrowded", esp: "superpoblado", unit: "File 9" },
  { eng: "pollution", esp: "contaminación", unit: "File 9" },
  { eng: "postgraduate", esp: "posgrado", unit: "File 9" },
  { eng: "racism", esp: "racismo", unit: "File 9" },
  { eng: "silence", esp: "silencio", unit: "File 9" },
  { eng: "strength", esp: "fuerza", unit: "File 9" },
  { eng: "subway", esp: "metro", unit: "File 9" },
  { eng: "success", esp: "éxito", unit: "File 9" },
  { eng: "thought", esp: "opinión", unit: "File 9" },
  { eng: "ugliness", esp: "fealdad", unit: "File 9" },
  { eng: "unbreakable", esp: "irrompible", unit: "File 9" },
  { eng: "underdeveloped", esp: "subdesarrollado", unit: "File 9" },
  { eng: "undrinkable", esp: "imbebible", unit: "File 9" },
  { eng: "useful", esp: "útil", unit: "File 9" },
  { eng: "vandalism", esp: "vandalismo", unit: "File 9" },
  { eng: "violence", esp: "violencia", unit: "File 9" },
  { eng: "waterproof", esp: "impermeable", unit: "File 9" },
  { eng: "weakness", esp: "punto débil", unit: "File 9" },
  { eng: "width", esp: "ancho", unit: "File 9" },
  { eng: "astronomer", esp: "astrónomo", unit: "File 10" },
  { eng: "astronomical", esp: "astronómico", unit: "File 10" },
  { eng: "astronomy", esp: "astronomía", unit: "File 10" },
  { eng: "biological", esp: "biológico", unit: "File 10" },
  { eng: "biologist", esp: "biólogo", unit: "File 10" },
  { eng: "biology", esp: "biología", unit: "File 10" },
  { eng: "botanical", esp: "botánico", unit: "File 10" },
  { eng: "botanist", esp: "botánico", unit: "File 10" },
  { eng: "botany", esp: "botánica", unit: "File 10" },
  { eng: "chemical", esp: "químico", unit: "File 10" },
  { eng: "chemist", esp: "químico", unit: "File 10" },
  { eng: "chemistry", esp: "química", unit: "File 10" },
  { eng: "clone", esp: "clon", unit: "File 10" },
  { eng: "discovery", esp: "descubrimiento", unit: "File 10" },
  { eng: "drugs", esp: "medicamento", unit: "File 10" },
  { eng: "experiment", esp: "experimento", unit: "File 10" },
  { eng: "genetic", esp: "genético", unit: "File 10" },
  { eng: "geneticist", esp: "genetista", unit: "File 10" },
  { eng: "genetics", esp: "genética", unit: "File 10" },
  { eng: "guinea pig", esp: "cobaya", unit: "File 10" },
  { eng: "laboratory", esp: "laboratorio", unit: "File 10" },
  { eng: "physical", esp: "físico", unit: "File 10" },
  { eng: "physicist", esp: "físico", unit: "File 10" },
  { eng: "physics", esp: "física", unit: "File 10" },
  { eng: "research", esp: "investigación", unit: "File 10" },
  { eng: "science", esp: "ciencia", unit: "File 10" },
  { eng: "scientific", esp: "científico", unit: "File 10" },
  { eng: "scientist", esp: "científico", unit: "File 10" },
  { eng: "side effect", esp: "efecto secundario", unit: "File 10" },
  { eng: "test", esp: "examen", unit: "File 10" },
  { eng: "theory", esp: "teoría", unit: "File 10" },
  { eng: "zoological", esp: "zoológico", unit: "File 10" },
  { eng: "zoologist", esp: "zoólogo", unit: "File 10" },
  { eng: "zoology", esp: "zoología", unit: "File 10" },
  { eng: "all or nothing", esp: "todo o nada", unit: "File 10" },
  { eng: "backwards and forwards", esp: "de un lado a otro", unit: "File 10" },
  { eng: "bits and pieces", esp: "cosita", unit: "File 10" },
  { eng: "by and large", esp: "en general", unit: "File 10" },
  { eng: "cause and effect", esp: "causa y efecto", unit: "File 10" },
  { eng: "dead or alive", esp: "vivo o muerto", unit: "File 10" },
  { eng: "forgive and forget", esp: "perdonar y olvidar", unit: "File 10" },
  { eng: "health and safety", esp: "salud y seguridad", unit: "File 10" },
  { eng: "law and order", esp: "ley y orden", unit: "File 10" },
  { eng: "live and learn", esp: "todos los días se aprende algo", unit: "File 10" },
  { eng: "more or less", esp: "más o menos", unit: "File 10" },
  { eng: "now and again", esp: "de vez en cuando", unit: "File 10" },
  { eng: "now or never", esp: "ahora o nunca", unit: "File 10" },
  { eng: "once or twice", esp: "una o dos veces", unit: "File 10" },
  { eng: "peace and quiet", esp: "paz y tranquilidad", unit: "File 10" },
  { eng: "pros and cons", esp: "pros y contras", unit: "File 10" },
  { eng: "rain or shine", esp: "llueva o truene", unit: "File 10" },
  { eng: "right or wrong", esp: "para bien o para mal", unit: "File 10" },
  { eng: "safe and sound", esp: "sano y salvo", unit: "File 10" },
  { eng: "short and sweet", esp: "bueno y breve", unit: "File 10" },
  { eng: "sick and tired", esp: "harto", unit: "File 10" },
  { eng: "sooner or later", esp: "tarde o temprano", unit: "File 10" },
  { eng: "supply and demand", esp: "oferta y demanda", unit: "File 10" },
  { eng: "thunder and lightning", esp: "rayos y truenos", unit: "File 10" },
  { eng: "touch and go", esp: "nunca se sabe", unit: "File 10" },
  { eng: "wait and see", esp: "espera y verás", unit: "File 10" }
];


// --- Lista para Español -> Inglés ---
// Contiene objetos con: { esp: "Palabra en Español", eng: "Traducción Inglés", unit: "Unidad" }
const listaEspIng = [
  { esp: "infalible", eng: "foolproof", unit: "File 1" },
  { esp: "friki", eng: "geek", unit: "File 1" },
  { esp: "rivalidad sana", eng: "good-natured rivalry", unit: "File 1" },
  { esp: "intuición", eng: "gut feeling", unit: "File 1" },
  { esp: "solicitante de empleo", eng: "job-seeker", unit: "File 1" },
  { esp: "respuesta desenfadada", eng: "light-hearted response", unit: "File 1" },
  { esp: "la cuestión", eng: "the point of", unit: "File 1" },
  { esp: "equilibrio entre la vida personal y laboral", eng: "work–life balance", unit: "File 1" },
  { esp: "distraído", eng: "absent-minded", unit: "File 1" },
  { esp: "de mal humor", eng: "bad-tempered", unit: "File 1" },
  { esp: "engreído", eng: "big-headed", unit: "File 1" },
  { esp: "de trato fácil", eng: "easy-going", unit: "File 1" },
  { esp: "sereno", eng: "good-tempered", unit: "File 1" },
  { esp: "despreocupado", eng: "laid-back", unit: "File 1" },
  { esp: "estrecho de miras", eng: "narrow-minded", unit: "File 1" },
  { esp: "abierto de mente", eng: "open-minded", unit: "File 1" },
  { esp: "egocéntrico", eng: "self-centred", unit: "File 1" },
  { esp: "de fuerte carácter", eng: "strong-willed", unit: "File 1" },
  { esp: "agarrado", eng: "tight-fisted", unit: "File 1" },
  { esp: "una persona falsa", eng: "two-faced", unit: "File 1" },
  { esp: "equilibrado", eng: "well-balanced", unit: "File 1" },
  { esp: "bien educados", eng: "well-behaved", unit: "File 1" },
  { esp: "reacción alérgica", eng: "allergic reaction", unit: "File 2" },
  { esp: "ponerse enfermo", eng: "be sick", unit: "File 2" },
  { esp: "sangrar", eng: "bleed", unit: "File 2" },
  { esp: "ampolla", eng: "blister", unit: "File 2" },
  { esp: "presión arterial (alta/baja)", eng: "(high / low) blood pressure", unit: "File 2" },
  { esp: "quemar", eng: "burn", unit: "File 2" },
  { esp: "atragantarse", eng: "choke", unit: "File 2" },
  { esp: "resfriado", eng: "cold", unit: "File 2" },
  { esp: "volver en sí", eng: "come round", unit: "File 2" },
  { esp: "tos", eng: "cough", unit: "File 2" },
  { esp: "cortarse", eng: "cut", unit: "File 2" },
  { esp: "diarrea", eng: "diarrhoea", unit: "File 2" },
  { esp: "mareado", eng: "dizzy", unit: "File 2" },
  { esp: "dolor de oído", eng: "earache", unit: "File 2" },
  { esp: "desmayarse", eng: "faint", unit: "File 2" },
  { esp: "sentirse enfermo", eng: "feel sick", unit: "File 2" },
  { esp: "gripe", eng: "flu", unit: "File 2" },
  { esp: "intoxicación alimentaria", eng: "food poisoning", unit: "File 2" },
  { esp: "curarse (de)", eng: "get over", unit: "File 2" },
  { esp: "dolor de cabeza", eng: "headache", unit: "File 2" },
  { esp: "doler", eng: "hurt", unit: "File 2" },
  { esp: "echarse", eng: "lie down", unit: "File 2" },
  { esp: "desmayarse", eng: "pass out", unit: "File 2" },
  { esp: "sarpullido", eng: "rash", unit: "File 2" },
  { esp: "dolor de garganta", eng: "sore throat", unit: "File 2" },
  { esp: "torcer(se)", eng: "sprain", unit: "File 2" },
  { esp: "dolor de estómago", eng: "stomach ache", unit: "File 2" },
  { esp: "quemarse por el sol", eng: "sunburn", unit: "File 2" },
  { esp: "dar de sí", eng: "swell", unit: "File 2" },
  { esp: "temperatura", eng: "temperature", unit: "File 2" },
  { esp: "vomitar", eng: "throw up", unit: "File 2" },
  { esp: "dolor de muelas", eng: "toothache", unit: "File 2" },
  { esp: "inconsciente", eng: "unconscious", unit: "File 2" },
  { esp: "vomitar", eng: "vomit", unit: "File 2" },
  { esp: "informal", eng: "casual", unit: "File 2" },
  { esp: "de cuadros", eng: "checked", unit: "File 2" },
  { esp: "clásico", eng: "classic", unit: "File 2" },
  { esp: "camiseta de algodón", eng: "cotton vest", unit: "File 2" },
  { esp: "chaleco vaquero", eng: "denim waistcoat", unit: "File 2" },
  { esp: "arreglarse", eng: "dress up", unit: "File 2" },
  { esp: "quedar bien (algo)", eng: "fit", unit: "File 2" },
  { esp: "estola de piel", eng: "fur collar", unit: "File 2" },
  { esp: "cambiarse", eng: "get changed", unit: "File 2" },
  { esp: "vestirse", eng: "get dressed", unit: "File 2" },
  { esp: "quitar(se) la ropa", eng: "get undressed", unit: "File 2" },
  { esp: "pegar (con)", eng: "go with", unit: "File 2" },
  { esp: "colgar", eng: "hang up", unit: "File 2" },
  { esp: "con capucha", eng: "hooded", unit: "File 2" },
  { esp: "top de encaje", eng: "lace top", unit: "File 2" },
  { esp: "sandalias de cuero", eng: "leather sandals", unit: "File 2" },
  { esp: "traje de lino", eng: "linen suit", unit: "File 2" },
  { esp: "de manga larga", eng: "long-sleeved", unit: "File 2" },
  { esp: "holgado", eng: "loose", unit: "File 2" },
  { esp: "bañador de lycra", eng: "lycra swimsuit", unit: "File 2" },
  { esp: "ir a juego", eng: "match", unit: "File 2" },
  { esp: "anticuado", eng: "old-fashioned", unit: "File 2" },
  { esp: "estampado", eng: "patterned", unit: "File 2" },
  { esp: "liso", eng: "plain", unit: "File 2" },
  { esp: "desaliñado", eng: "scruffy", unit: "File 2" },
  { esp: "pañuelo de seda", eng: "silk scarf", unit: "File 2" },
  { esp: "sin mangas", eng: "sleeveless", unit: "File 2" },
  { esp: "elegante", eng: "smart", unit: "File 2" },
  { esp: "de lunares", eng: "spotted", unit: "File 2" },
  { esp: "de rayas", eng: "striped", unit: "File 2" },
  { esp: "botas de ante", eng: "suede boots", unit: "File 2" },
  { esp: "quedar bien (algo)", eng: "suit", unit: "File 2" },
  { esp: "apretado", eng: "tight", unit: "File 2" },
  { esp: "pajarita de terciopelo", eng: "velvet bow tie", unit: "File 2" },
  { esp: "cuello de pico", eng: "V-neck", unit: "File 2" },
  { esp: "rebeca de lana", eng: "wool(len) cardigan", unit: "File 2" },
  { esp: "terminal de aeropuerto", eng: "airport terminal", unit: "File 3" },
  { esp: "pasillo", eng: "aisle", unit: "File 3" },
  { esp: "mostrador de equipajes", eng: "bag(gage) drop", unit: "File 3" },
  { esp: "recogida de equipajes", eng: "baggage reclaim", unit: "File 3" },
  { esp: "embarcar", eng: "board", unit: "File 3" },
  { esp: "tarjeta de embarque", eng: "boarding pass", unit: "File 3" },
  { esp: "business", eng: "business", unit: "File 3" },
  { esp: "personal de cabina", eng: "cabin crew", unit: "File 3" },
  { esp: "inspeccionar", eng: "check", unit: "File 3" },
  { esp: "facturar", eng: "check in", unit: "File 3" },
  { esp: "mostrador de facturación", eng: "check-in desk", unit: "File 3" },
  { esp: "cerrado", eng: "closed", unit: "File 3" },
  { esp: "recoger", eng: "collect", unit: "File 3" },
  { esp: "vuelo de enlace", eng: "connecting flight", unit: "File 3" },
  { esp: "aduana", eng: "customs", unit: "File 3" },
  { esp: "retrasado", eng: "delayed", unit: "File 3" },
  { esp: "panel de salidas", eng: "departures board", unit: "File 3" },
  { esp: "vuelo directo", eng: "direct flight", unit: "File 3" },
  { esp: "llevar (a alguien)", eng: "drop off", unit: "File 3" },
  { esp: "primera clase", eng: "first class", unit: "File 3" },
  { esp: "hora del vuelo", eng: "flight time", unit: "File 3" },
  { esp: "rellenar", eng: "fill in", unit: "File 3" },
  { esp: "puerta", eng: "gate", unit: "File 3" },
  { esp: "bajar(se) (de algo)", eng: "get off", unit: "File 3" },
  { esp: "subir(se) (a algo)", eng: "get on", unit: "File 3" },
  { esp: "equipaje de mano", eng: "hand luggage", unit: "File 3" },
  { esp: "productos ilegales", eng: "illegal goods", unit: "File 3" },
  { esp: "desfase horario", eng: "jet lag", unit: "File 3" },
  { esp: "viaje", eng: "journey", unit: "File 3" },
  { esp: "aterrizar", eng: "land", unit: "File 3" },
  { esp: "líquido", eng: "liquid", unit: "File 3" },
  { esp: "vuelo de larga distancia", eng: "long-haul flight", unit: "File 3" },
  { esp: "sala (de compañía aérea)", eng: "(airline) lounge", unit: "File 3" },
  { esp: "equipaje", eng: "luggage", unit: "File 3" },
  { esp: "puntual", eng: "on time", unit: "File 3" },
  { esp: "recoger (algo)", eng: "pick up", unit: "File 3" },
  { esp: "recoger (a alguien)", eng: "pick up", unit: "File 3" },
  { esp: "fila", eng: "row", unit: "File 3" },
  { esp: "pista", eng: "runway", unit: "File 3" },
  { esp: "pasar por el escáner", eng: "scan", unit: "File 3" },
  { esp: "cinturón de seguridad", eng: "seat belt", unit: "File 3" },
  { esp: "seguridad", eng: "security", unit: "File 3" },
  { esp: "objeto punzante", eng: "sharp object", unit: "File 3" },
  { esp: "despegar", eng: "take off", unit: "File 3" },
  { esp: "viajar", eng: "travel", unit: "File 3" },
  { esp: "viaje", eng: "trip", unit: "File 3" },
  { esp: "carrito", eng: "trolley", unit: "File 3" },
  { esp: "turbulencia", eng: "turbulence", unit: "File 3" },
  { esp: "en realidad", eng: "actually", unit: "File 3" },
  { esp: "al parecer", eng: "apparently", unit: "File 3" },
  { esp: "al final", eng: "at the end", unit: "File 3" },
  { esp: "en estos momentos", eng: "at the moment", unit: "File 3" },
  { esp: "sencillamente", eng: "basically", unit: "File 3" },
  { esp: "desde luego", eng: "certainly", unit: "File 3" },
  { esp: "especialmente", eng: "especially", unit: "File 3" },
  { esp: "incluso", eng: "even", unit: "File 3" },
  { esp: "al final", eng: "eventually", unit: "File 3" },
  { esp: "alguna vez", eng: "ever", unit: "File 3" },
  { esp: "poco a poco", eng: "gradually", unit: "File 3" },
  { esp: "duro", eng: "hard", unit: "File 3" },
  { esp: "apenas", eng: "hardly", unit: "File 3" },
  { esp: "(lo) ideal", eng: "ideally", unit: "File 3" },
  { esp: "en realidad", eng: "in fact", unit: "File 3" },
  { esp: "al final", eng: "in the end", unit: "File 3" },
  { esp: "tarde", eng: "late", unit: "File 3" },
  { esp: "últimamente", eng: "lately", unit: "File 3" },
  { esp: "cerca", eng: "near", unit: "File 3" },
  { esp: "casi", eng: "nearly", unit: "File 3" },
  { esp: "obviamente", eng: "obviously", unit: "File 3" },
  { esp: "expresamente", eng: "specially", unit: "File 3" },
  { esp: "todavía", eng: "still", unit: "File 3" },
  { esp: "aún", eng: "yet", unit: "File 3" },
  { esp: "bajo cero", eng: "below zero", unit: "File 4" },
  { esp: "ventisca", eng: "blizzard", unit: "File 4" },
  { esp: "hacer un calor sofocante", eng: "boiling", unit: "File 4" },
  { esp: "brisa", eng: "breeze", unit: "File 4" },
  { esp: "brillante", eng: "bright", unit: "File 4" },
  { esp: "variable", eng: "changeable", unit: "File 4" },
  { esp: "fresco", eng: "chilly", unit: "File 4" },
  { esp: "despejado", eng: "clear", unit: "File 4" },
  { esp: "fresco", eng: "cool", unit: "File 4" },
  { esp: "húmedo", eng: "damp", unit: "File 4" },
  { esp: "lloviznar", eng: "drizzle", unit: "File 4" },
  { esp: "sequía", eng: "drought", unit: "File 4" },
  { esp: "inundación", eng: "flood", unit: "File 4" },
  { esp: "niebla", eng: "fog", unit: "File 4" },
  { esp: "hacer mucho frío", eng: "freezing", unit: "File 4" },
  { esp: "granizo", eng: "hail", unit: "File 4" },
  { esp: "ola de calor", eng: "heatwave", unit: "File 4" },
  { esp: "intenso", eng: "heavy", unit: "File 4" },
  { esp: "húmedo", eng: "humid", unit: "File 4" },
  { esp: "huracán", eng: "hurricane", unit: "File 4" },
  { esp: "helado", eng: "icy", unit: "File 4" },
  { esp: "relámpago", eng: "lightning", unit: "File 4" },
  { esp: "templado", eng: "mild", unit: "File 4" },
  { esp: "neblina", eng: "mist", unit: "File 4" },
  { esp: "monzón", eng: "monsoon", unit: "File 4" },
  { esp: "llover a mares", eng: "pour (with rain)", unit: "File 4" },
  { esp: "estable", eng: "settled", unit: "File 4" },
  { esp: "tormenta", eng: "shower", unit: "File 4" },
  { esp: "contaminación", eng: "smog", unit: "File 4" },
  { esp: "fuerte", eng: "strong", unit: "File 4" },
  { esp: "soleado", eng: "sunny", unit: "File 4" },
  { esp: "denso", eng: "thick", unit: "File 4" },
  { esp: "trueno", eng: "thunder", unit: "File 4" },
  { esp: "calor", eng: "warm", unit: "File 4" },
  { esp: "aprovechar", eng: "take advantage of", unit: "File 4" },
  { esp: "parecerse (a alguien)", eng: "take after", unit: "File 4" },
  { esp: "estar enfadado", eng: "take against", unit: "File 4" },
  { esp: "encargarse de", eng: "take care of", unit: "File 4" },
  { esp: "tener en cuenta", eng: "take into account", unit: "File 4" },
  { esp: "no hacer caso de", eng: "take no notice of", unit: "File 4" },
  { esp: "despegar", eng: "take off", unit: "File 4" },
  { esp: "quitarse (algo)", eng: "take (sth) off", unit: "File 4" },
  { esp: "llevar (a alguien)", eng: "take (sb) out", unit: "File 4" },
  { esp: "sacar (fuera)", eng: "take (sth) out", unit: "File 4" },
  { esp: "participar en", eng: "take part in", unit: "File 4" },
  { esp: "apiadarse de", eng: "take pity on", unit: "File 4" },
  { esp: "tener lugar", eng: "take place", unit: "File 4" },
  { esp: "tomar riesgos", eng: "take risks", unit: "File 4" },
  { esp: "tomarse el tiempo necesario", eng: "take (your) time", unit: "File 4" },
  { esp: "encariñarse con", eng: "take to", unit: "File 4" },
  { esp: "empezar a hacer algo", eng: "take up", unit: "File 4" },
  { esp: "asombrado", eng: "astonished", unit: "File 5" },
  { esp: "perplejo", eng: "bewildered", unit: "File 5" },
  { esp: "encantado", eng: "delighted", unit: "File 5" },
  { esp: "desesperado", eng: "desperate", unit: "File 5" },
  { esp: "devastado", eng: "devastated", unit: "File 5" },
  { esp: "decepcionado", eng: "disappointed", unit: "File 5" },
  { esp: "decaído", eng: "down", unit: "File 5" },
  { esp: "harto", eng: "fed up", unit: "File 5" },
  { esp: "atónito", eng: "gobsmacked", unit: "File 5" },
  { esp: "agradecido", eng: "grateful", unit: "File 5" },
  { esp: "quedarse hecho polvo", eng: "gutted", unit: "File 5" },
  { esp: "tener nostalgia", eng: "homesick", unit: "File 5" },
  { esp: "horrorizado", eng: "horrifed", unit: "File 5" },
  { esp: "solo", eng: "lonely", unit: "File 5" },
  { esp: "abatido", eng: "miserable", unit: "File 5" },
  { esp: "ofendido", eng: "offended", unit: "File 5" },
  { esp: "abrumado", eng: "overwhelmed", unit: "File 5" },
  { esp: "orgulloso", eng: "proud", unit: "File 5" },
  { esp: "aliviado", eng: "relieved", unit: "File 5" },
  { esp: "muerto de miedo", eng: "scared stiff", unit: "File 5" },
  { esp: "hecho añicos", eng: "shattered", unit: "File 5" },
  { esp: "harto de", eng: "sick of", unit: "File 5" },
  { esp: "aturdido", eng: "stunned", unit: "File 5" },
  { esp: "entusiasmado", eng: "thrilled", unit: "File 5" },
  { esp: "disgustado", eng: "upset", unit: "File 5" },
  { esp: "asombrar", eng: "amaze", unit: "File 5" },
  { esp: "confundir", eng: "confuse", unit: "File 5" },
  { esp: "decepcionar", eng: "disappoint", unit: "File 5" },
  { esp: "avergonzar", eng: "embarrass", unit: "File 5" },
  { esp: "agotado", eng: "exhaust", unit: "File 5" },
  { esp: "frustrar", eng: "frustrate", unit: "File 5" },
  { esp: "enfurecer", eng: "infuriate", unit: "File 5" },
  { esp: "inspirar", eng: "inspire", unit: "File 5" },
  { esp: "aterrorizar", eng: "terrify", unit: "File 5" },
  { esp: "hacer (mucha) ilusión", eng: "thrill", unit: "File 5" },
  { esp: "tener un sueño ligero", eng: "be a light sleeper", unit: "File 6" },
  { esp: "dormirse rápido", eng: "be fast asleep", unit: "File 6" },
  { esp: "manta", eng: "blanket", unit: "File 6" },
  { esp: "edredón", eng: "duvet", unit: "File 6" },
  { esp: "dormirse", eng: "fall asleep", unit: "File 6" },
  { esp: "tener pesadillas", eng: "have nightmares", unit: "File 6" },
  { esp: "insomnio", eng: "insomnia", unit: "File 6" },
  { esp: "impedir dormir", eng: "keep you awake", unit: "File 6" },
  { esp: "siesta", eng: "nap", unit: "File 6" },
  { esp: "quedarse dormido", eng: "oversleep", unit: "File 6" },
  { esp: "almohada", eng: "pillow", unit: "File 6" },
  { esp: "poner la alarma", eng: "set the alarm", unit: "File 6" },
  { esp: "sábana", eng: "sheet", unit: "File 6" },
  { esp: "pastilla para dormir", eng: "sleeping pill", unit: "File 6" },
  { esp: "dormir como un tronco", eng: "sleep like a log", unit: "File 6" },
  { esp: "ser sonámbulo", eng: "sleepwalk", unit: "File 6" },
  { esp: "tener sueño", eng: "sleepy", unit: "File 6" },
  { esp: "roncar", eng: "snore", unit: "File 6" },
  { esp: "bostezar", eng: "yawn", unit: "File 6" },
  { esp: "arquitectura", eng: "architecture", unit: "File 6" },
  { esp: "ballet", eng: "ballet", unit: "File 6" },
  { esp: "barista", eng: "barista", unit: "File 6" },
  { esp: "bajo", eng: "bass guitar", unit: "File 6" },
  { esp: "ramo", eng: "bouquet", unit: "File 6" },
  { esp: "capuchino", eng: "cappuccino", unit: "File 6" },
  { esp: "violonchelo", eng: "cello", unit: "File 6" },
  { esp: "chófer", eng: "chauffeur", unit: "File 6" },
  { esp: "chef", eng: "chef", unit: "File 6" },
  { esp: "elegante", eng: "chic", unit: "File 6" },
  { esp: "coro", eng: "choir", unit: "File 6" },
  { esp: "estribillo", eng: "chorus", unit: "File 6" },
  { esp: "concierto", eng: "concerto", unit: "File 6" },
  { esp: "director", eng: "conductor", unit: "File 6" },
  { esp: "croissant", eng: "croissant", unit: "File 6" },
  { esp: "tambor", eng: "drum", unit: "File 6" },
  { esp: "bis", eng: "encore", unit: "File 6" },
  { esp: "prometido", eng: "fiancé", unit: "File 6" },
  { esp: "flauta", eng: "flute", unit: "File 6" },
  { esp: "género", eng: "genre", unit: "File 6" },
  { esp: "grafiti", eng: "graffiti", unit: "File 6" },
  { esp: "hipocondríaco", eng: "hypochondriac", unit: "File 6" },
  { esp: "teclado", eng: "keyboard", unit: "File 6" },
  { esp: "macchiato", eng: "macchiato", unit: "File 6" },
  { esp: "mezzo-soprano", eng: "mezzo-soprano", unit: "File 6" },
  { esp: "micrófono", eng: "microphone", unit: "File 6" },
  { esp: "orquesta", eng: "orchestra", unit: "File 6" },
  { esp: "paparazzi", eng: "paparazzi", unit: "File 6" },
  { esp: "filosofía", eng: "philosophy", unit: "File 6" },
  { esp: "adivino", eng: "psychic", unit: "File 6" },
  { esp: "psicólogo", eng: "psychologist", unit: "File 6" },
  { esp: "ritmo", eng: "rhythm", unit: "File 6" },
  { esp: "saxofón", eng: "saxophone", unit: "File 6" },
  { esp: "soprano", eng: "soprano", unit: "File 6" },
  { esp: "sinfonía", eng: "symphony", unit: "File 6" },
  { esp: "chalet", eng: "villa", unit: "File 6" },
  { esp: "violín", eng: "violin", unit: "File 6" },
  { esp: "aconsejar", eng: "advise", unit: "File 7" },
  { esp: "argumentar", eng: "argue", unit: "File 7" },
  { esp: "evitar", eng: "avoid", unit: "File 7" },
  { esp: "derrotar", eng: "beat", unit: "File 7" },
  { esp: "pedir prestado", eng: "borrow", unit: "File 7" },
  { esp: "negar", eng: "deny", unit: "File 7" },
  { esp: "hablar (de algo)", eng: "discuss", unit: "File 7" },
  { esp: "esperar", eng: "expect", unit: "File 7" },
  { esp: "esperar", eng: "hope", unit: "File 7" },
  { esp: "poner (la mesa...)", eng: "lay (past laid)", unit: "File 7" },
  { esp: "prestar", eng: "lend", unit: "File 7" },
  { esp: "tumbarse", eng: "lie (past lay)", unit: "File 7" },
  { esp: "importar", eng: "matter", unit: "File 7" },
  { esp: "importar", eng: "mind", unit: "File 7" },
  { esp: "darse cuenta", eng: "notice", unit: "File 7" },
  { esp: "impedir", eng: "prevent", unit: "File 7" },
  { esp: "subir", eng: "raise", unit: "File 7" },
  { esp: "darse cuenta (de)", eng: "realize", unit: "File 7" },
  { esp: "negarse", eng: "refuse", unit: "File 7" },
  { esp: "acordarse (de)", eng: "remember", unit: "File 7" },
  { esp: "recordar (algo a alguien)", eng: "remind", unit: "File 7" },
  { esp: "subir", eng: "rise", unit: "File 7" },
  { esp: "robar", eng: "rob", unit: "File 7" },
  { esp: "robar", eng: "steal", unit: "File 7" },
  { esp: "esperar", eng: "wait", unit: "File 7" },
  { esp: "advertir", eng: "warn", unit: "File 7" },
  { esp: "ganar", eng: "win", unit: "File 7" },
  { esp: "ojalá", eng: "wish", unit: "File 7" },
  { esp: "tobillo", eng: "ankle", unit: "File 7" },
  { esp: "morderse las uñas", eng: "bite your nails", unit: "File 7" },
  { esp: "sonarse la nariz", eng: "blow your nose", unit: "File 7" },
  { esp: "trasero", eng: "bottom", unit: "File 7" },
  { esp: "cerebro", eng: "brain", unit: "File 7" },
  { esp: "cepillarse el pelo", eng: "brush your hair", unit: "File 7" },
  { esp: "lavarse los dientes", eng: "brush your teeth", unit: "File 7" },
  { esp: "pantorrilla", eng: "calf", unit: "File 7" },
  { esp: "mejilla", eng: "cheek", unit: "File 7" },
  { esp: "pecho", eng: "chest", unit: "File 7" },
  { esp: "masticar", eng: "chew", unit: "File 7" },
  { esp: "barbilla", eng: "chin", unit: "File 7" },
  { esp: "peinarse", eng: "comb your hair", unit: "File 7" },
  { esp: "codo", eng: "elbow", unit: "File 7" },
  { esp: "ojo", eng: "eye", unit: "File 7" },
  { esp: "ceja", eng: "eyebrow", unit: "File 7" },
  { esp: "pestaña", eng: "eyelash", unit: "File 7" },
  { esp: "párpado", eng: "eyelid", unit: "File 7" },
  { esp: "puño", eng: "fist", unit: "File 7" },
  { esp: "cruzarse de brazos", eng: "fold your arms", unit: "File 7" },
  { esp: "frente", eng: "forehead", unit: "File 7" },
  { esp: "fruncir el ceño", eng: "frown", unit: "File 7" },
  { esp: "corazón", eng: "heart", unit: "File 7" },
  { esp: "tacón", eng: "heel", unit: "File 7" },
  { esp: "cadera", eng: "hip", unit: "File 7" },
  { esp: "coger a alguien de la mano", eng: "hold someone's hand", unit: "File 7" },
  { esp: "abrazar", eng: "hug", unit: "File 7" },
  { esp: "riñón", eng: "kidneys", unit: "File 7" },
  { esp: "rodilla", eng: "knee", unit: "File 7" },
  { esp: "arrodillarse", eng: "kneel", unit: "File 7" },
  { esp: "labio", eng: "lips", unit: "File 7" },
  { esp: "hígado", eng: "liver", unit: "File 7" },
  { esp: "pulmón", eng: "lungs", unit: "File 7" },
  { esp: "uñas", eng: "nails", unit: "File 7" },
  { esp: "cuello", eng: "neck", unit: "File 7" },
  { esp: "palma", eng: "palm", unit: "File 7" },
  { esp: "señalar", eng: "point", unit: "File 7" },
  { esp: "levantar las cejas", eng: "raise your eyebrows", unit: "File 7" },
  { esp: "rascar", eng: "scratch", unit: "File 7" },
  { esp: "darse la mano", eng: "shake hands", unit: "File 7" },
  { esp: "negar con la cabeza", eng: "shake your head", unit: "File 7" },
  { esp: "encogerse de hombros", eng: "shrug your shoulders", unit: "File 7" },
  { esp: "mirar fijamente", eng: "stare", unit: "File 7" },
  { esp: "estirar(se)", eng: "stretch", unit: "File 7" },
  { esp: "vello", eng: "stubble", unit: "File 7" },
  { esp: "chuparse el dedo", eng: "suck your thumb", unit: "File 7" },
  { esp: "muslo", eng: "thigh", unit: "File 7" },
  { esp: "tocarse los dedos de los pies", eng: "touch your toes", unit: "File 7" },
  { esp: "cintura", eng: "waist", unit: "File 7" },
  { esp: "saludar", eng: "wave", unit: "File 7" },
  { esp: "guiñar el ojo", eng: "wink", unit: "File 7" },
  { esp: "arruga", eng: "wrinkles", unit: "File 7" },
  { esp: "muñeca", eng: "wrist", unit: "File 7" },
  { esp: "bostezar", eng: "yawn", unit: "File 7" },
  { esp: "acusar", eng: "accuse", unit: "File 8" },
  { esp: "absolver", eng: "acquit", unit: "File 8" },
  { esp: "detener", eng: "arrest", unit: "File 8" },
  { esp: "chantajear", eng: "blackmail", unit: "File 8" },
  { esp: "sobornar", eng: "bribery", unit: "File 8" },
  { esp: "robo (de una casa)", eng: "burglary", unit: "File 8" },
  { esp: "atrapar", eng: "catch", unit: "File 8" },
  { esp: "acusar", eng: "charge", unit: "File 8" },
  { esp: "cometer", eng: "commit", unit: "File 8" },
  { esp: "tribunal", eng: "court", unit: "File 8" },
  { esp: "tráfico de drogas", eng: "drug dealing", unit: "File 8" },
  { esp: "prueba", eng: "evidence", unit: "File 8" },
  { esp: "fraude", eng: "fraud", unit: "File 8" },
  { esp: "culpable", eng: "guilty", unit: "File 8" },
  { esp: "hackeo", eng: "hacking", unit: "File 8" },
  { esp: "secuestrar", eng: "hijacking", unit: "File 8" },
  { esp: "inocente", eng: "innocent", unit: "File 8" },
  { esp: "investigar", eng: "investigate", unit: "File 8" },
  { esp: "juez", eng: "judge", unit: "File 8" },
  { esp: "jurado", eng: "jury", unit: "File 8" },
  { esp: "secuestro", eng: "kidnapping", unit: "File 8" },
  { esp: "asalto", eng: "mugging", unit: "File 8" },
  { esp: "asesinato", eng: "murder", unit: "File 8" },
  { esp: "prueba", eng: "proof", unit: "File 8" },
  { esp: "castigo", eng: "punishment", unit: "File 8" },
  { esp: "interrogar", eng: "question", unit: "File 8" },
  { esp: "violación", eng: "rape", unit: "File 8" },
  { esp: "robo", eng: "robbery", unit: "File 8" },
  { esp: "sentencia", eng: "sentence", unit: "File 8" },
  { esp: "contrabando", eng: "smuggling", unit: "File 8" },
  { esp: "acoso", eng: "stalking", unit: "File 8" },
  { esp: "terrorismo", eng: "terrorism", unit: "File 8" },
  { esp: "robo", eng: "theft", unit: "File 8" },
  { esp: "vandalismo", eng: "vandalism", unit: "File 8" },
  { esp: "veredicto", eng: "verdict", unit: "File 8" },
  { esp: "testigo", eng: "witness", unit: "File 8" },
  { esp: "preciso", eng: "accurate", unit: "File 8" },
  { esp: "columnista de consultorio sentimental", eng: "agony aunt", unit: "File 8" },
  { esp: "perder (empleos)", eng: "axe", unit: "File 8" },
  { esp: "respaldar", eng: "back", unit: "File 8" },
  { esp: "parcial", eng: "biased", unit: "File 8" },
  { esp: "intentar", eng: "bid", unit: "File 8" },
  { esp: "censurado", eng: "censored", unit: "File 8" },
  { esp: "discutir", eng: "clash", unit: "File 8" },
  { esp: "comentarista", eng: "commentator", unit: "File 8" },
  { esp: "crítico", eng: "critic", unit: "File 8" },
  { esp: "editor", eng: "editor", unit: "File 8" },
  { esp: "periodista freelance", eng: "freelance journalist", unit: "File 8" },
  { esp: "afectar", eng: "hit", unit: "File 8" },
  { esp: "presentador de noticias", eng: "newsreader", unit: "File 8" },
  { esp: "objetivo", eng: "objective", unit: "File 8" },
  { esp: "paparazzi", eng: "paparazzi", unit: "File 8" },
  { esp: "presentador", eng: "presenter", unit: "File 8" },
  { esp: "dimitir (de)", eng: "quit", unit: "File 8" },
  { esp: "interrogar", eng: "quiz", unit: "File 8" },
  { esp: "reportero", eng: "reporter", unit: "File 8" },
  { esp: "discutir", eng: "row", unit: "File 8" },
  { esp: "sensacionalista", eng: "sensational", unit: "File 8" },
  { esp: "separarse", eng: "split", unit: "File 8" },
  { esp: "predecir", eng: "tip", unit: "File 8" },
  { esp: "prometer", eng: "vow", unit: "File 8" },
  { esp: "casarse (con)", eng: "wed", unit: "File 8" },
  { esp: "campaña de publicidad", eng: "advertising campaign", unit: "File 9" },
  { esp: "anuncios", eng: "advertisments", unit: "File 9" },
  { esp: "marca", eng: "brand", unit: "File 9" },
  { esp: "afirmar", eng: "claims", unit: "File 9" },
  { esp: "consumidor", eng: "consumers", unit: "File 9" },
  { esp: "engañoso", eng: "misleading", unit: "File 9" },
  { esp: "publicidad", eng: "publicity", unit: "File 9" },
  { esp: "eslogan", eng: "slogan", unit: "File 9" },
  { esp: "demandar", eng: "sue", unit: "File 9" },
  { esp: "algún otro tema", eng: "any other business", unit: "File 9" },
  { esp: "convertirse en el líder del mercado", eng: "become the market leader", unit: "File 9" },
  { esp: "explosión", eng: "boom", unit: "File 9" },
  { esp: "sucursal", eng: "branch", unit: "File 9" },
  { esp: "cadena", eng: "chain", unit: "File 9" },
  { esp: "cerrar", eng: "close down", unit: "File 9" },
  { esp: "hacer un trato", eng: "do a deal", unit: "File 9" },
  { esp: "hacer un trabajo", eng: "do a job", unit: "File 9" },
  { esp: "ir mal", eng: "do badly", unit: "File 9" },
  { esp: "hacer negocios", eng: "do business", unit: "File 9" },
  { esp: "hacer un estudio de mercado", eng: "do market research", unit: "File 9" },
  { esp: "hacer (algo) bien", eng: "do well", unit: "File 9" },
  { esp: "disminuir", eng: "drop", unit: "File 9" },
  { esp: "expandir(se)", eng: "expand", unit: "File 9" },
  { esp: "exportar", eng: "export", unit: "File 9" },
  { esp: "fracaso", eng: "flop", unit: "File 9" },
  { esp: "ponerse a trabajar", eng: "get down to business", unit: "File 9" },
  { esp: "quebrar (negocio)", eng: "go out of business", unit: "File 9" },
  { esp: "crecer", eng: "grow", unit: "File 9" },
  { esp: "sede central", eng: "head office", unit: "File 9" },
  { esp: "importar", eng: "import", unit: "File 9" },
  { esp: "lanzamiento", eng: "launch", unit: "File 9" },
  { esp: "tomar una decisión", eng: "make a decision", unit: "File 9" },
  { esp: "tener pérdidas", eng: "make a loss", unit: "File 9" },
  { esp: "tener beneficios", eng: "make a profit", unit: "File 9" },
  { esp: "ganar dinero", eng: "make money", unit: "File 9" },
  { esp: "despedir (a alguien) por exceso de personal", eng: "make (sb) redundant", unit: "File 9" },
  { esp: "fabricar", eng: "manufacture", unit: "File 9" },
  { esp: "actuar en serio", eng: "mean business", unit: "File 9" },
  { esp: "fusionar(se)", eng: "merge", unit: "File 9" },
  { esp: "meterse en sus asuntos", eng: "mind your own business", unit: "File 9" },
  { esp: "mezclar negocios y placer", eng: "mix business with pleasure", unit: "File 9" },
  { esp: "no es asunto tuyo", eng: "none of your business", unit: "File 9" },
  { esp: "producir", eng: "produce", unit: "File 9" },
  { esp: "recesión", eng: "recession", unit: "File 9" },
  { esp: "fundar(se)", eng: "set up", unit: "File 9" },
  { esp: "absorber", eng: "take over", unit: "File 9" },
  { esp: "asunto pendiente", eng: "unfinished business", unit: "File 9" },
  { esp: "ausencia", eng: "absence", unit: "File 9" },
  { esp: "abundancia", eng: "abundance", unit: "File 9" },
  { esp: "alojamiento", eng: "accommodation", unit: "File 9" },
  { esp: "alcoholismo", eng: "alcoholism", unit: "File 9" },
  { esp: "antisocial", eng: "antisocial", unit: "File 9" },
  { esp: "piloto automático", eng: "autopilot", unit: "File 9" },
  { esp: "creencia", eng: "belief", unit: "File 9" },
  { esp: "bilingüe", eng: "bilingual", unit: "File 9" },
  { esp: "fraternidad", eng: "brotherhood", unit: "File 9" },
  { esp: "a prueba de balas", eng: "bulletproof", unit: "File 9" },
  { esp: "tener cuidado", eng: "careful", unit: "File 9" },
  { esp: "infancia", eng: "childhood", unit: "File 9" },
  { esp: "frío", eng: "coldness", unit: "File 9" },
  { esp: "relación", eng: "connection", unit: "File 9" },
  { esp: "comodidad", eng: "convenience", unit: "File 9" },
  { esp: "muerte", eng: "death", unit: "File 9" },
  { esp: "desarrollo", eng: "development", unit: "File 9" },
  { esp: "distancia", eng: "distance", unit: "File 9" },
  { esp: "trabajo", eng: "employment", unit: "File 9" },
  { esp: "entretenimiento", eng: "entertainment", unit: "File 9" },
  { esp: "emoción", eng: "excitement", unit: "File 9" },
  { esp: "expectativa", eng: "expectation", unit: "File 9" },
  { esp: "amabilidad", eng: "friendliness", unit: "File 9" },
  { esp: "gobierno", eng: "government", unit: "File 9" },
  { esp: "calor", eng: "heat", unit: "File 9" },
  { esp: "altura", eng: "height", unit: "File 9" },
  { esp: "sin techo", eng: "homeless", unit: "File 9" },
  { esp: "desesperado", eng: "hopeless", unit: "File 9" },
  { esp: "hambre", eng: "hunger", unit: "File 9" },
  { esp: "ignorancia", eng: "ignorance", unit: "File 9" },
  { esp: "mejora", eng: "improvement", unit: "File 9" },
  { esp: "intención", eng: "intention", unit: "File 9" },
  { esp: "soledad", eng: "loneliness", unit: "File 9" },
  { esp: "pérdida", eng: "loss", unit: "File 9" },
  { esp: "megaciudad", eng: "megacity", unit: "File 9" },
  { esp: "entender mal", eng: "misunderstood", unit: "File 9" },
  { esp: "modernismo", eng: "modernism", unit: "File 9" },
  { esp: "monorraíl", eng: "monorail", unit: "File 9" },
  { esp: "multicultural", eng: "multicultural", unit: "File 9" },
  { esp: "barrio", eng: "neighbourhood", unit: "File 9" },
  { esp: "superpoblado", eng: "overcrowded", unit: "File 9" },
  { esp: "contaminación", eng: "pollution", unit: "File 9" },
  { esp: "posgrado", eng: "postgraduate", unit: "File 9" },
  { esp: "racismo", eng: "racism", unit: "File 9" },
  { esp: "silencio", eng: "silence", unit: "File 9" },
  { esp: "fuerza", eng: "strength", unit: "File 9" },
  { esp: "metro", eng: "subway", unit: "File 9" },
  { esp: "éxito", eng: "success", unit: "File 9" },
  { esp: "opinión", eng: "thought", unit: "File 9" },
  { esp: "fealdad", eng: "ugliness", unit: "File 9" },
  { esp: "irrompible", eng: "unbreakable", unit: "File 9" },
  { esp: "subdesarrollado", eng: "underdeveloped", unit: "File 9" },
  { esp: "imbebible", eng: "undrinkable", unit: "File 9" },
  { esp: "útil", eng: "useful", unit: "File 9" },
  { esp: "vandalismo", eng: "vandalism", unit: "File 9" },
  { esp: "violencia", eng: "violence", unit: "File 9" },
  { esp: "impermeable", eng: "waterproof", unit: "File 9" },
  { esp: "punto débil", eng: "weakness", unit: "File 9" },
  { esp: "ancho", eng: "width", unit: "File 9" },
  { esp: "astrónomo", eng: "astronomer", unit: "File 10" },
  { esp: "astronómico", eng: "astronomical", unit: "File 10" },
  { esp: "astronomía", eng: "astronomy", unit: "File 10" },
  { esp: "biológico", eng: "biological", unit: "File 10" },
  { esp: "biólogo", eng: "biologist", unit: "File 10" },
  { esp: "biología", eng: "biology", unit: "File 10" },
  { esp: "botánico", eng: "botanical", unit: "File 10" },
  { esp: "botánico", eng: "botanist", unit: "File 10" },
  { esp: "botánica", eng: "botany", unit: "File 10" },
  { esp: "químico", eng: "chemical", unit: "File 10" },
  { esp: "químico", eng: "chemist", unit: "File 10" },
  { esp: "química", eng: "chemistry", unit: "File 10" },
  { esp: "clon", eng: "clone", unit: "File 10" },
  { esp: "descubrimiento", eng: "discovery", unit: "File 10" },
  { esp: "medicamento", eng: "drugs", unit: "File 10" },
  { esp: "experimento", eng: "experiment", unit: "File 10" },
  { esp: "genético", eng: "genetic", unit: "File 10" },
  { esp: "genetista", eng: "geneticist", unit: "File 10" },
  { esp: "genética", eng: "genetics", unit: "File 10" },
  { esp: "cobaya", eng: "guinea pig", unit: "File 10" },
  { esp: "laboratorio", eng: "laboratory", unit: "File 10" },
  { esp: "físico", eng: "physical", unit: "File 10" },
  { esp: "físico", eng: "physicist", unit: "File 10" },
  { esp: "física", eng: "physics", unit: "File 10" },
  { esp: "investigación", eng: "research", unit: "File 10" },
  { esp: "ciencia", eng: "science", unit: "File 10" },
  { esp: "científico", eng: "scientific", unit: "File 10" },
  { esp: "científico", eng: "scientist", unit: "File 10" },
  { esp: "efecto secundario", eng: "side effect", unit: "File 10" },
  { esp: "examen", eng: "test", unit: "File 10" },
  { esp: "teoría", eng: "theory", unit: "File 10" },
  { esp: "zoológico", eng: "zoological", unit: "File 10" },
  { esp: "zoólogo", eng: "zoologist", unit: "File 10" },
  { esp: "zoología", eng: "zoology", unit: "File 10" },
  { esp: "todo o nada", eng: "all or nothing", unit: "File 10" },
  { esp: "de un lado a otro", eng: "backwards and forwards", unit: "File 10" },
  { esp: "cosita", eng: "bits and pieces", unit: "File 10" },
  { esp: "en general", eng: "by and large", unit: "File 10" },
  { esp: "causa y efecto", eng: "cause and effect", unit: "File 10" },
  { esp: "vivo o muerto", eng: "dead or alive", unit: "File 10" },
  { esp: "perdonar y olvidar", eng: "forgive and forget", unit: "File 10" },
  { esp: "salud y seguridad", eng: "health and safety", unit: "File 10" },
  { esp: "ley y orden", eng: "law and order", unit: "File 10" },
  { esp: "todos los días se aprende algo", eng: "live and learn", unit: "File 10" },
  { esp: "más o menos", eng: "more or less", unit: "File 10" },
  { esp: "de vez en cuando", eng: "now and again", unit: "File 10" },
  { esp: "ahora o nunca", eng: "now or never", unit: "File 10" },
  { esp: "una o dos veces", eng: "once or twice", unit: "File 10" },
  { esp: "paz y tranquilidad", eng: "peace and quiet", unit: "File 10" },
  { esp: "pros y contras", eng: "pros and cons", unit: "File 10" },
  { esp: "llueva o truene", eng: "rain or shine", unit: "File 10" },
  { esp: "para bien o para mal", eng: "right or wrong", unit: "File 10" },
  { esp: "sano y salvo", eng: "safe and sound", unit: "File 10" },
  { esp: "bueno y breve", eng: "short and sweet", unit: "File 10" },
  { esp: "harto", eng: "sick and tired", unit: "File 10" },
  { esp: "tarde o temprano", eng: "sooner or later", unit: "File 10" },
  { esp: "oferta y demanda", eng: "supply and demand", unit: "File 10" },
  { esp: "rayos y truenos", eng: "thunder and lightning", unit: "File 10" },
  { esp: "nunca se sabe", eng: "touch and go", unit: "File 10" },
  { esp: "espera y verás", eng: "wait and see", unit: "File 10" }
];
